module dsubs_client.colorscheme;

import derelict.sfml2.graphics;

/*

#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=1000u0k3V4WaYgf7Lb1ac80gJaQ


*** Primary color:

   shade 0 = #272222 = rgb( 39, 34, 34) = rgba( 39, 34, 34,1) = rgb0(0.153,0.133,0.133)
   shade 1 = #815555 = rgb(129, 85, 85) = rgba(129, 85, 85,1) = rgb0(0.506,0.333,0.333)
   shade 2 = #584343 = rgb( 88, 67, 67) = rgba( 88, 67, 67,1) = rgb0(0.345,0.263,0.263)
   shade 3 = #402B2B = rgb( 64, 43, 43) = rgba( 64, 43, 43,1) = rgb0(0.251,0.169,0.169)
   shade 4 = #562929 = rgb( 86, 41, 41) = rgba( 86, 41, 41,1) = rgb0(0.337,0.161,0.161)


#####  Generated by Paletton.com (c) 2002-2014

*/

struct ColorScheme
{
	sfColor renderClear = sfColor(39, 34, 34, 255);
	sfColor defaultFont = sfWhite;
	sfColor textFieldBgnd = sfColor(64, 43, 43, 255);
	sfColor textFieldCursor = sfRed;
	sfColor simPanelBgnd = sfColor(10, 0, 0, 100);
	sfColor simButtonBgnd = sfColor(20, 14, 14, 200);
	sfColor simButtonDisabledBgnd = sfColor(255, 15, 15, 20);
	sfColor simButtonDisabledFont = sfColor(0, 0, 0, 40);
	sfColor simButtonSelectedStateBgnd = sfColor(86, 41, 41, 200);
	sfColor simLaunchButtonBgnd = sfColor(200, 50, 50, 255);
	sfColor simMessageFont = sfColor(189, 135, 135, 255);
}

/// Global color scheme
__gshared ColorScheme COLORS;